import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.pool.OracleDataSource;
import java.io.IOException;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author TestEnv
 */
public class create extends javax.swing.JFrame {

    /**
     * Creates new form createaccount1
     */
    Connection con;
    public create() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        signupbut = new javax.swing.JButton();
        logbutt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        passtxt = new javax.swing.JPasswordField();
        phone = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Fname = new javax.swing.JTextField();
        Mname = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        skills = new javax.swing.JTextField();
        showpass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Downloads\\c.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        signupbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbutActionPerformed(evt);
            }
        });
        getContentPane().add(signupbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 653, 350, 50));

        logbutt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logbuttMouseClicked(evt);
            }
        });
        logbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbuttActionPerformed(evt);
            }
        });
        getContentPane().add(logbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 730, -1, 30));

        passtxt.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        phone.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        phone.setToolTipText("");

        Address.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        Fname.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        Mname.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        emailtxt.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        Lname.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Lname.setToolTipText("");

        skills.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(763, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(411, Short.MAX_VALUE)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(785, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(212, Short.MAX_VALUE)
                    .addComponent(Mname, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(983, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1182, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(763, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(763, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(14, Short.MAX_VALUE)
                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(806, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(skills, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(765, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(247, Short.MAX_VALUE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(485, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(153, Short.MAX_VALUE)
                    .addComponent(Lname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(580, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(154, Short.MAX_VALUE)
                    .addComponent(Mname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(580, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(154, Short.MAX_VALUE)
                    .addComponent(Fname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(582, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(574, Short.MAX_VALUE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(416, Short.MAX_VALUE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(333, Short.MAX_VALUE)
                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(399, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(497, Short.MAX_VALUE)
                    .addComponent(skills, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        getContentPane().add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 330, 40, 40));

        setSize(new java.awt.Dimension(1382, 793));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logbuttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbuttMouseClicked
        login INK= new login();
       INK.show();
       dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_logbuttMouseClicked

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
if(showpass.isSelected()){ passtxt.setEchoChar((char)0);}
 else passtxt.setEchoChar('*');
// TODO add your handling code here:
    }//GEN-LAST:event_showpassActionPerformed

    private void logbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbuttActionPerformed
dispose();//close signup page
                login log = new login();
                log.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_logbuttActionPerformed
public boolean checkemailexist(String email){
       boolean checkemail = false;
        try {
            String url="jdbc:oracle:thin:@localhost:1521:xe";

        con = DriverManager.getConnection(url, "c##mylinecnter", "654321");  
       
        ResultSet rs;
        String query ="SELECT * FROM EMPLOYEE WHERE email = ? ";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, emailtxt.getText());
            rs = ps.executeQuery();
            if(rs.next())
                checkemail = true;    
        }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
        } 
        return checkemail;
}
    private void signupbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbutActionPerformed
     String Firstname = Fname.getText();
                String Middlename = Mname.getText();
                String Lastname = Lname.getText();  
                String email = emailtxt.getText();
                String password =String.valueOf(passtxt.getPassword());
                String phonenum = phone.getText();
                String address = Address.getText();
                String skill = skills.getText();
                
                
                if(Firstname.trim().isEmpty())
                        JOptionPane.showMessageDialog(null, "Please Add your  First Name.");
                else if(Middlename.trim().isEmpty())
                        JOptionPane.showMessageDialog(null, "Please Add your Middle Name. ");
                else if(Lastname.trim().isEmpty())
                        JOptionPane.showMessageDialog(null, "Please Add your Last Name. ");
                else if(email.trim().isEmpty())
                        JOptionPane.showMessageDialog(null, "Please Add your email.");
                else if(phonenum.trim().isEmpty())
                        JOptionPane.showMessageDialog(null, "Please Add your Phone number.");
                else if(password.trim().isEmpty())
                        JOptionPane.showMessageDialog(null, "Please Add your password.");
                else if(address.trim().isEmpty())
                        JOptionPane.showMessageDialog(null, "Please Add your Address.");
                else if(skill.trim().isEmpty())
                        JOptionPane.showMessageDialog(null, "Please Add your Skills.");
                else if(checkemailexist(email))  
                        JOptionPane.showMessageDialog(null, "This email is already exist, try another email to register");
                

                else {
  String url="jdbc:oracle:thin:@localhost:1521:xe";
                                       String sql = "INSERT INTO EMPLOYEE (FNAME,MNAME,LNAME,EMAIL,ADDRESS,PHONE,SKILLS,PASSWORD) VALUES (?, ?, ?, ?, ? ,?, ?, ?)";
   
              
                try {
                      
                     con = DriverManager.getConnection(url, "c##mylinecnter", "654321");   
          
                PreparedStatement statement = con.prepareStatement(sql); 
                
                statement.setString(1, Firstname);
                statement.setString(2, Middlename);
                statement.setString(3, Lastname);
                statement.setString(4, email);
                statement.setString(5,address);
                statement.setString(6, phonenum);
                statement.setString(7, skill);
                statement.setString(8, password);
                statement.executeUpdate();
                                                      
                
                JOptionPane.showMessageDialog(null, "Sign up successful.");       
          con.close();
                
                } 
                catch(Exception e){
                JOptionPane.showMessageDialog(null,"Sign up failed");
            }
}        // TODO add your handling code here:
    }//GEN-LAST:event_signupbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Fname;
    private javax.swing.JTextField Lname;
    private javax.swing.JTextField Mname;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logbutt;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JTextField phone;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JButton signupbut;
    private javax.swing.JTextField skills;
    // End of variables declaration//GEN-END:variables
}
