/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author TestEnv
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class selectpage extends javax.swing.JFrame {
 login log=new login();
    /**
     * Creates new form selectpage
     */

    
    Connection con;
    public selectpage() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        toolsbut = new javax.swing.JButton();
        studentbut = new javax.swing.JButton();
        employeebut = new javax.swing.JButton();
        COURSE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\LineProject\\wajhattt\\selectttt.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        toolsbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toolsbutMouseClicked(evt);
            }
        });
        toolsbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsbutActionPerformed(evt);
            }
        });
        getContentPane().add(toolsbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 170, 50));

        studentbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentbutMouseClicked(evt);
            }
        });
        getContentPane().add(studentbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 170, 40));

        employeebut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeebutMouseClicked(evt);
            }
        });
        getContentPane().add(employeebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, 50));

        COURSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COURSEActionPerformed(evt);
            }
        });
        getContentPane().add(COURSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 170, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toolsbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolsbutMouseClicked
      tools INK = new tools();
      INK.show();
      dispose();
     
    }//GEN-LAST:event_toolsbutMouseClicked

    private void studentbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentbutMouseClicked
         student INK = new student();
      INK.show();
      dispose();
     
    }//GEN-LAST:event_studentbutMouseClicked

     
    private void toolsbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsbutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toolsbutActionPerformed

   
    private void COURSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COURSEActionPerformed
courses INK= new courses();
INK.show();
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_COURSEActionPerformed

    private void employeebutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeebutMouseClicked
 employee emp = new employee();
    emp.show();
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_employeebutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton COURSE;
    private javax.swing.JButton employeebut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton studentbut;
    private javax.swing.JButton toolsbut;
    // End of variables declaration//GEN-END:variables
}
